server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-customer
  data:
    mongodb:
      username: usr-customer-mongo
      password: pwd-customer-mongo
      database: customer-dev-mongo
      port: 27017
      host: localhost

info:
  application:
    name: api-customer

eureka:
   healthcheck:
     enabled: true
   instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/